openapi: 3.0.1
info:
  title: TransformFuncApp
  description: Import from "TransformFuncApp" Function App
  version: '1.0'
servers:
  - url: https://trainingapimoauth.azure-api.net/TransformFuncApp
paths:
  /ParentFunction:
    post:
      summary: ParentFunction
      description: ParentFunction
      operationId: post-parentfunction
      responses:
        '200':
          description: ''
components:
  securitySchemes:
    apiKeyHeader:
      type: apiKey
      name: Ocp-Apim-Subscription-Key
      in: header
    apiKeyQuery:
      type: apiKey
      name: subscription-key
      in: query
security:
  - apiKeyHeader: [ ]
  - apiKeyQuery: [ ]