apimServiceName: APIM-Prod-ci-cd
namedValues: 
  - name: backendIdName
    properties:
      displayName: backendIdName
      value: "trainingfunctionappcg"
  - name: Aud-Training
    properties:
      displayName: Aud-Training
      value: "b8c65e8b-b988-452b-91d4-75ddf6200a79"
  - name: tenant-training
    properties:
      displayName: tenant-training
      value: "aadaa7c6-824c-4ebe-aeab-2e4712904ca6"
  - name: transformfuncapp-key
    properties:
      displayName: transformfuncapp-key
      value: "4zlxboXng4kGONnO0NCmV-2NX7Ln16wUTVm6bfC1rIqjAzFunDaIiA=="
  - name: 682eae08feac1630f1fade87
    properties:
      displayName: laapicall_laapicall_682eae08feac1630f1fade87
      value: "q70uumJ2gGI1fsGMFlr0TUc0l529vYYC69vjACk1m_M"
loggers:
diagnostics:
backends:
  - name: trainingfunctionappcg
    properties:
      url: "https://trainingfunctionappcg.azurewebsites.net/api"
      resourceId: "https://management.azure.com/subscriptions/86986ba7-9d80-464e-bbed-2157e2dd5997/resourceGroups/Training/providers/Microsoft.Web/sites/trainingfunctionappcg"
  - name: LogicApp_transform-LA_Training_86986ba79d80464ebbed2157e2dd5997
    properties:
      url: "https://prod-12.northcentralus.logic.azure.com:443/workflows/a8a040da227346058f9c4ac9df9a5c2e/triggers"
      resourceId: "https://management.azure.com/subscriptions/86986ba7-9d80-464e-bbed-2157e2dd5997/resourceGroups/APIM-Prod/providers/Microsoft.Logic/workflows/ProdLA"
apis:
